#!/bin/bash

###############################################################################
# SNARTomoAnimate
#
# Changelog:
#   2023-06-23 (trs) -- 
#
###############################################################################

function program_info() {
  echo 
  echo "Running: SNARTomoAnimate"
  echo "Modified 2023-06-27"
  date
  echo 
}

#################### Filenames and Parameters ####################

shared_libs=snartomo-shared-23jun.bash  # Shared libraries
bin_factor=1                            # Downsampling factor
frame_rate=25                           # Frame rate of movie
movie_format=mpg                        # Movie format
verbosity=2                             # Verbosity level (Max: 4)

################ END BATCH HEADER ################

# Outline (multiline comment)
: '
main
  check_env
  parse_command_line
  shared.check_args
  shared.check_dir
  shared.check_exe
  get_axis
    shared.get_shortest_axis
  shared.set_local_dir
  movie_convert
  shared.clean_local_dir
'

function main() {
###############################################################################
#   Passed arguments:
#     ${@} : command-line arguments
#   
###############################################################################
  
  # BASH arrays can't be returned, so declare them here
  declare -A original_vars
  declare -a var_sequence
  declare -A vars
  
  check_env
  parse_command_line "${@}"
  check_args 1 1
  fn="${ARGS[0]}"
  
  if [[ "${vars[verbosity]}" -ge 2 ]] ; then
    echo "Validating..."
  fi
  check_dir "${vars[imod_dir]}" "IMOD executables directory"
  check_exe "$(which ffmpeg)" "FFMPEG executable"
  vprint "" "2+"
  
  get_axis
  
  # Prevent potential conflicts with full SNARTomo runs
  vars[temp_local]="./.$(basename $SNARTOMO_LOCAL)-animate"
  
  if [[ "${vars[testing]}" == false ]]; then
    set_local_dir
  fi
  
  movie_convert
  
  if [[ "${vars[testing]}" == false ]] && [[ "${vars[keep]}" == false ]] ; then
    clean_local_dir
  fi
}

function check_env() {
###############################################################################
#   Functions:
#     Checks whether environmental variable SNARTOMO_DIR is set
#     Sources shared functions from central SNARTomo directory
#     
#   Calls functions:
#     check_vars
#   
#   Global variables:
#     do_pace
#     shared_libs
#     
###############################################################################

  if [[ "${SNARTOMO_DIR}" == "" ]]; then
    echo -e "\nERROR!! Environmental variable 'SNARTOMO_DIR' undefined!"
    echo      "  Set variable with: export SNARTOMO_DIR=<path_to_snartomo_files>"
    echo -e   "  Exiting...\n"
    exit
  else
    source "${SNARTOMO_DIR}/${shared_libs}"
    source "${SNARTOMO_DIR}/argumentparser_dynamic.sh"
  fi
}

function parse_command_line() {
###############################################################################
#   Function:
#     Parses command line
#   
#   Passed arguments:
#     ${@} : command-line arguments
#   
#   Global variables:
#     original_vars : non-associative array, before cleaning
#     var_sequence : associative array, maintaining the order of the variables
#     vars : final options array
#   
###############################################################################
  
  add_argument "bin" "${bin_factor}" "Downsampling factor" "INT"
  add_argument "output" "AUTO" "Output filename stem (w/o extension, default->stem of input)" "ANY"
  add_argument "axis" "AUTO" "Axis to animate (stack -> 'z')" "ANY"
  add_argument "fps" "${frame_rate}" "Frames per second" "FLOAT"
  add_argument "bps" "AUTO" "Bit rate, bits per second" "ANY"
  add_argument "format" "${movie_format}" "Movie format" "ANY"
  add_argument "verbosity" "${verbosity}" "Verbosity level (0..4)" "INT"
  
  add_section "ADVANCED SETTINGS" "These settings will rarely need to be changed."
  add_argument "testing" "false" "Testing flag" "BOOL"
  add_argument "keep" "false" "Flag to keep intermediates" "BOOL"
  add_argument "imod_dir" "${IMOD_BIN}" "IMOD executable directory" "ANY"
  add_argument "temp_local" "${SNARTOMO_LOCAL}" "Directory for temporary files" "ANY"

  dynamic_parser "${@}"
#   print_vars
#   printf "'%s'\n" "${ARGS[@]}" ; exit

  if [[ "${vars[verbosity]}" -ge 2 ]] ; then
    verbose="${vars[verbosity]}"
  fi
}

function print_usage() {
  echo "USAGE : $(basename $0) MRC stack/volume <options>"
  echo
  echo "To list options & defaults, type:"
  echo "  $(basename $0) --help"
}

function get_axis() {
###############################################################################
#   Function:
#     FUNCTION
#   
#   Positional variables:
#   
#   Calls functions:
#     get_shortest_axis
#   
#   Global variables:
#     axis_array (OUTPUT)
#     min_dim
#     min_idx
#     min_axis (OUTPUT)
#   
###############################################################################
  
  axis_array=("x" "y" "z")
  
  if [[ "${vars[axis]}" == "AUTO" ]] ; then
    get_shortest_axis
    min_axis="-${axis_array[$min_idx]}"
  # #   echo "min_dim '$min_dim', min_idx '$min_idx', min_axis '$min_axis'" ; exit
  else
    min_axis="-${vars[axis]}"
    
    # Need index
    for idx in "${!axis_array[@]}"; do
      if [[ "${axis_array[$idx]}" == "${vars[axis]}" ]]; then
        min_idx=$idx
      fi
    done
  fi
}

function set_local_dir() {
###############################################################################
#   Function:
#     Set local directory if necessary
#   
#   Global variables:
#     vars
#     temp_local_dir (OUTPUT)
#     verbose
#   
###############################################################################
  
  # In case we need to copy EERs locally, remember the PID ($$)
  temp_local_dir="${vars[temp_local]}/$$"
  
  if [[ "$verbose" -ge 2 ]]; then
    mkdir -pv "${temp_local_dir}" 2> /dev/null
  else
    mkdir -p "${temp_local_dir}" 2> /dev/null
  fi
}

function movie_convert() {
###############################################################################
#   Function:
#     Downsample, convert 
#   
#   Positional variables:
#   
#   Calls functions:
#   
#   Global variables:
#     temp_local_dir
#     axis_array
#     min_axis
#     min_idx
#     fn
#     verbose
#   
###############################################################################
  
  local img_format="jpg"  # for intermediate files
  local stderr="${temp_local_dir}/stderr.$$"
  
  if [[ "${vars[verbosity]}" -ge 1 ]] ; then
    local dimension_string=$(${vars[imod_dir]}/header $fn | grep sections | xargs | rev | cut -d' ' -f1-3 | rev)
    
    if [[ "${vars[testing]}" == false ]]; then
      echo
    fi
    
    echo "Dimensions of $fn: $dimension_string"
  fi
  
  # Remove shortest axis from axis arracy
  unset "axis_array[$min_idx]"
  
  # Build command line
  local bin_cmd="${vars[imod_dir]}/binvol"
  
  # add downsampling factor for each axis except along the unstacking axis
  for idx in "${!axis_array[@]}"; do
    bin_cmd+=" -${axis_array[$idx]} ${vars[bin]}"
  done
  
  local out_prefix="${temp_local_dir}/$(echo $fn | rev | cut -d'.' -f 2- | rev)"
  local out_bin="${out_prefix}_bin2.mrc"
  bin_cmd+=" ${min_axis} 1 $fn $out_bin"
  vprint "  Running: $bin_cmd" "1+"
  
  if [[ "${vars[testing]}" == false ]]; then
    if [[ $verbose -ge 3 ]] ; then
      $bin_cmd
    else
      $bin_cmd > /dev/null
    fi
  fi
  
  if [[ $img_format == "png" ]] ; then
    local format_flag='-p'
  else
    local format_flag='-j'
  fi
  
  local tif_cmd="${vars[imod_dir]}/mrc2tif ${format_flag} $out_bin ${out_prefix}"
  vprint "  Running: $tif_cmd" "1+"
  
  if [[ "${vars[testing]}" == false ]]; then
    if [[ $verbose -ge 3 ]] ; then
      $tif_cmd
    else
      $tif_cmd > /dev/null
    fi
    
    local new_dimensions=$(${vars[imod_dir]}/header $out_bin | grep sections | xargs | rev | cut -d' ' -f1-3 | rev)
    \rm $out_bin
  fi
  
  # Build ffmpeg command
  local movie_cmd="ffmpeg -y -framerate ${vars[fps]} -i ${out_prefix}.%03d.${img_format}"
  
  if [[ "${vars[output]}" == "AUTO" ]]; then
    vars[output]="$(basename ${out_prefix}.${vars[format]})"
  fi
  
  # Default bit rate is file size divided by framte rate
  if [[ "${vars[bps]}" == "AUTO" ]]; then
    vars[bps]=$(echo $(ls -s $fn | cut -d ' ' -f 1) / ${vars[fps]} | bc)
  fi
  
  local movie_cmd="ffmpeg -y -framerate ${vars[fps]} -i ${out_prefix}.%03d.${img_format} -b:v ${vars[bps]}k ${vars[output]}"
  vprint "  Running: $movie_cmd" "1+"
  
  if [[ "${vars[testing]}" == false ]]; then
    if [[ $verbose -ge 3 ]] ; then
      $movie_cmd | tee ${stderr}
      local status_code=$?
    else
      $movie_cmd 2> ${stderr}
      local status_code=$?
    fi
    
    # Sanity check
    if [[ "${status_code}" != 0 ]] ; then
      echo -e "\nERROR!! FFMPEG failed!"
      echo      "Error message:"
      
      # Better would be to print the lines after "Press [q] to stop, [?] for help"
      tail -n 3 ${stderr} | sed 's/^/  /'
      echo -e "\nExiting...\n"
      exit
    else
      if [[ "${vars[verbosity]}" -ge 1 ]] ; then
        local bit_rate=$(ffprobe ${vars[output]} 2>&1 | grep Duration | rev | cut -d ' ' -f 1-2 | rev)
        echo -e "Dimensions of ${vars[output]}: $new_dimensions, bit rate $bit_rate"
      fi
    fi
    
    # Clean up
    if [[ "${vars[keep]}" == false ]]; then
      \rm ${out_prefix}*.${img_format}
      \rm ${stderr}
    fi
  fi
}

function DUMMY_FUNCTION() {
###############################################################################
#   Function:
#     FUNCTION
#   
#   Positional variables:
#   
#   Calls functions:
#   
#   Global variables:
#   
###############################################################################
  
  return
}

########################################################################################

main "$@"
